name: Production release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.6
          run_install: false

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: pnpm

      - name: Set secrets
        run: |
          npx sst secrets load .env --stage production

      - name: Deploy stack
        run: pnpm deploy --stage production
        env:
          CI: true
