name: Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Copy .env.example to .env
        run: |
          cp .env.example .env

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.6.1
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Perform basic audit
        run: pnpm audit --audit-level high

      - name: Perform quality checks
        id: quality-checks
        run: |
          pnpm run format:check
          pnpm run lint

      - name: Build
        id: build
        run: |
          pnpm run build
